main: fr.cinpiros.SmcTask
name: smcTask
version: 1.0
api-version: 1.19
commands:
  task:
    description: task base command
    usage: /task
    aliases: [t, tasks]
    permission: smcTask.admin.access
    permission-message: "&cVous n'avez pas la permission néssésaire pour exécuter cette commande"
